# 项目名称（必须）
spring.application.name: sia-task-intask

# 应用端口号（必须）
server.port: 10091

# zookeeper地址（必须）
zooKeeperHosts: 127.0.0.1:2181
zooKeeperSessionTime: 2000

# 应用上下文（可选）
server.context-path: /

# 是否开启 AOP 切面功能（默认为true）
spring.aop.auto: true

# 是否开启 @OnlineTask 串行控制（如果使用则必须开启AOP功能）（默认为true）（可选）
spring.onlinetask.serial: true

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/siatask?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

# mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sia.core.entity

#注册中心地址
eureka.client.serviceUrl.defaultZone: http://127.0.0.1:61352/eureka/

# 注册时使用ip而不是主机名
eureka.instance.preferIpAddress: true
# ${spring.cloud.client.ipAddress} 为IP地址
eureka.instance.instance-id: ${spring.cloud.client.ipAddress}:${server.port}

# 预警邮件配置
SKYTRAIN_DEFAULT_EMAIL:
EMAIL_SERVICE_REQUESTPATH: http://127.0.0.1:12026/v1/sendEmail

logging.file: ./logs/${spring.application.name}.log

#ZK_ONLINE_ROOT_PATH: SkyWorldOnlineTask